version: 2.1

orbs:
  node: circleci/node@5.0.0
  heroku: circleci/heroku@1.2.6

workflows:
  build-tests:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          force: true
          requires:
            - node/test
          filters:
            branches:
              only: master
